name: Run Tests

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: false
          load: true
          tags: plm-interpretability:test

      - name: Run tests in Docker container
        run: |
          docker run --rm plm-interpretability:test pytest tests/
